### ISSUE TITLE
reserved_ip for private IPv4

### ISSUE THREAD

**Issue by johnstudarus** [packethost/terraform-provider-packet#128]
Any reason why there isn't support for private address allocations? Seems like it would be an easy feature to add (underlying API supports it).

```
resource "packet_reserved_ip_block" "my_private_elastic_ip" {
  project_id = "${var.packet_project_id}"
  facility   = "ewr1"
  type       = "private_ipv4"                        # new feature <---------------
  quantity   = 1
}
```

**Comment by johnstudarus** [comment]
Interesting...

Through the GUI, you can request a private_ipv4 block by clicking on the server first and then drilling down. But if you click through from the project network, you can't get request a private_ipv4 block...

**Comment by t0mk** [comment]
IIUC, from the device -> Network section in the UI, you don't request blocks, you just assign private IP from pre-allocated private IPv4 block in the facility. The private IPv4 block is allocated in the facilility when you run a device in the faciltiy. 

Theoretically, it should be possible to assign IP from a block with the precreated_ip_block datasource. It might not be srtaightforward though, because the block will not exists before the (first) device is created in a faciltiy.

**Comment by displague** [comment]
The ability to assign private IPs dynamically, after the initial provision, could be possible with https://github.com/equinix/terraform-provider-metal/issues/12#issuecomment-775268639. I'm not sure if it would be possible to change those addresses after the port has been toggled to Layer3 for the first time (perhaps the provider would need to convert to layer2 and back to layer3 to add additional addresses?). I believe there is a limit of 1 private IP range per device.

In any case, I'm closing this issue as this provider is being deprecated in favor of the Equinix Metal provider 
https://github.com/equinix/terraform-provider-metal

Let's bring this issue up again over there if there is still interest.
