### ISSUE TITLE
Modifying user_data doesn't force device re-creation

### ISSUE THREAD

**Issue by johananl** [packethost/terraform-provider-packet#236]
### Terraform Version

```
Terraform v0.12.24
+ provider.packet v2.8.0
```

### Affected Resource(s)

- packet_device

### Expected Behavior

Modifying the `user_data` attribute of a Packet device should force resource re-creation.

### Actual Behavior

Modifying the `user_data` attribute of a Packet device does not force resource re-creation.

### Steps to Reproduce

1. Create a `resource "packet_device"` with some value in `user_data`.
1. Run `terraform apply`.
1. Modify the value in `user_data`.
1. Run `terraform plan`.

**Comment by t0mk** [comment]
hi @johananl thanks for your report, I will take a look tomorrow.

**Comment by t0mk** [comment]
hmm, there's been a request from someone from Packet to make it not ForceNew: https://github.com/terraform-providers/terraform-provider-packet/pull/169

@jmarhee do you remember why we've set user_date not to force re-creation on change? It was some elaborate scenario IIRC, but I don't remember what exactly.

**Comment by jmarhee** [comment]
@t0mk I recall recreating the device was a breaking change, but do not recall off-hand to what. I'm looking into this to see if I can find the original context for why we needed this flipped off at the time. I'll keep you updated.

**Comment by jmarhee** [comment]
@t0mk It appears that a customer reported that updating user_data via the API/Portal worked correctly, but it did not via Terraform, so we disabled it here; I believe this may have, since, been addressed, but I do not have confirmation on this. We can go ahead and test this with the setting reverted to confirm possibly, but beyond that, this was the high-level explanation for the change in the first place.

**Comment by johananl** [comment]
FWIW, here are my thoughts on this:

User data is used to provision cloud machines. I'm not aware of any other use for user data. Since cloud machines are typically treated as immutable, at least with regards to configuration options typically handled by user data scripts, I find it strange that altering the user data *at the API level* is even possible. AFAICT, the only way this capability is useful is if the user somehow re-runs `cloud-init` or whatever script they use for provisioning so that the updated config takes place. Personally I've never seen this scenario used in practice: in immutable environments you replace the machines on any config change and in mutable environments you don't rely on user data for machine configuration to begin with (and rather use tools like Ansible or Chef). On the other hand, AWS EC2 allows editing user data when an instance is stopped, so perhaps there is a sense in having this option.

Assuming it does make sense to allow editing user data on the Packet API, I guess we have two questions here:

1. Does it make sense to have the option of altering user data via Terraform without replacing the machine?
1. Assuming the answer to the previous question is "yes", should it be possible to force a replacement when altering user data (that is, without "manual" operations such as `terraform taint`)?

If it helps, AWS seems to allow editing user data on the API, **however** doing so via Terraform forces a replacement of the instance.

**Comment by t0mk** [comment]
@johananl @jmarhee 
Concluding from your last comments, I will make userdata ForceNew. I will pay close attention to support traffic if/until it breaks someone else's setup.

**Comment by t0mk** [comment]
I will ping you here when new release with ForceNew on userdata is ready.

**Comment by johananl** [comment]
Thanks a lot @t0mk.

>I will pay close attention to support traffic if/until it breaks someone else's setup.

Just for emphasis, my comment above describes what makes sense to *me* personally. I'm not familiar with all possible use cases so it's very likely that some people actually like being able to modify user data on running instances.

**Comment by t0mk** [comment]
@johananl it's released. Please do `terraform init -upgrade` and check if it works for you. You can close the issue if it does then.

**Comment by johananl** [comment]
Running `terraform init` with and without `-upgrade` using the following version constraints in my `.tf` file:

```hcl
terraform {
  required_version = ">= 0.12.0"

  required_providers {
    packet   = "= 2.10.0"
  }
}
```

Getting the following:

```
Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

No provider "packet" plugins meet the constraint "= 2.10.0".

The version constraint is derived from the "version" argument within the
provider "packet" block in configuration. Child modules may also apply
provider version constraints. To view the provider versions requested by each
module in the current configuration, run "terraform providers".

To proceed, the version constraints for this provider must be relaxed by
either adjusting or removing the "version" argument in the provider blocks
throughout the configuration.


Error: no suitable version is available
```

Doing the same with `2.9.0` works fine. Do you know if Terraform pulls the providers directly from GitHub? Where is the binary stored?

**Comment by johananl** [comment]
Ah, the provider downloads now :clap: Testing.

**Comment by johananl** [comment]
Confirmed that modifying `user_data` triggers a replacement now. Thank you @t0mk!
In case anybody complains about the change, maybe there is a way to make it user-configurable (I don't have a lot of experience with TF providers).

**Comment by jstangroome** [comment]
Hello, this change breaks our usage. :)

Since particular server types are in limited supply in various Packet regions, we've found it more reliable to update the userdata in place and then re-image the existing server (the `reinstall` device API action). Destroying an existing server and then re-provisioning often leads to capacity errors, manual retries, and support ticket escalations.

If we use `lifecycle { ignore_changes = ["user_data"] }` to avoid the re-provision I believe we also lose the updating of the userdata.

**Comment by ivan-section-io** [comment]
Highly contentious issue. See https://github.com/terraform-providers/terraform-provider-aws/issues/23

Not sure if there's a clear answer one way or another. 

Just don't do anything where a minor provider upgrade would suddenly destroy people's servers... oh.

Oh, my...

**Comment by t0mk** [comment]
@jstangroome @ivan-section-io thanks for your comments.

We need to get Packet people look at this @displague , maybe you can review.

I think the userdata ForceNew issue is either one way or another. Right now I can't think of a functioning compromise.

**Comment by t0mk** [comment]
Maybe there could be 2 conflicting attributes - user_data and user_data_forcenew. One would be forcenew and users could choose which one to use.

**Comment by johananl** [comment]
> Maybe there could be 2 conflicting attributes - user_data and user_data_forcenew. One would be forcenew and users could choose which one to use.

What would make more sense to me personally is to have another attribute under `packet_device` which determines whether to replace on user data change. Not sure if forcing a new resource can be "computed" in Terraform though.

**Comment by johananl** [comment]
https://github.com/terraform-providers/terraform-provider-packet/blob/5c8dd1f220cadf36cbc87aff4edda6b967010ed0/packet/resource_packet_device.go#L233-L238

Can we set `ForceNew` conditionally? At the Go level I don't see why not.

**Comment by t0mk** [comment]
@johananl AFAIK you can't set ForceNew conditionally as an attribute in a resource in a TF provider, it's a boolean, interpreted directly by the TF sdk.

Theoretically we could unset the ForceNew, and create a new optional bool attr taint_on_userdata_change, which would be true by default. If set, the resource logic would force to recreate on user_data change.

I think it could be done with CustomizeDiff of the Resource struct
https://godoc.org/github.com/hashicorp/terraform-plugin-sdk/helper/schema#Resource
but it's a very dirty solution.

Till then @ivan-section-io @jstangroome I guess you know that you can fix your provider version to 2.9.0.

**Comment by jstangroome** [comment]
@t0mk 

>2 conflicting attributes - user_data and user_data_forcenew.

Of all the workarounds, this feels the least hacky. I also feel like there may be prior art in another provider somewhere, I'll dig around.

>I guess you know that you can fix your provider version to 2.9.0.

Yep, done, thanks.

**Comment by t0mk** [comment]
@jstangroome 
> I also feel like there may be prior art in another provider somewhere, I'll dig around.

That would be really helpful!

@displague @jmarhee Do you have any Packet-official opinion on handling this?

**Comment by jstangroome** [comment]
>I also feel like there may be prior art in another provider somewhere, I'll dig around.

Where `user_data` forces new in Terraform:
* [AWS](https://github.com/terraform-providers/terraform-provider-aws/blob/e11ab5c4f868aca78b745ede1b05c7e8a1510dc0/aws/resource_aws_instance.go#L142)
* [DigitalOcean](https://github.com/terraform-providers/terraform-provider-digitalocean/blob/289c96e90b670f3a6f12858f1d3bf8602284d5a0/digitalocean/resource_digitalocean_droplet.go#L170)
* [Azure](https://github.com/terraform-providers/terraform-provider-azurerm/blob/a92df50c4c97cd98a163edfe94c2d7420e550dae/azurerm/internal/tf/base64/schema.go#L15)

Where it doesn't:
* [Google](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_instance.go#L440-L445): `metadata["user-data"]` can be updated in-place but `metadata["startup-script"]` is pulled into a separate `metadata_startup_script` argument and is marked `ForceNew`.
* [Alibaba Cloud](https://github.com/terraform-providers/terraform-provider-alicloud/blob/master/alicloud/resource_alicloud_instance.go#L1226-L1238): `user_data` can be updated in-place but will reboot the machine.

When I was thinking of prior art, I was mistakenly thinking of this:

`aws_db_instance` has an [apply_immediately](https://www.terraform.io/docs/providers/aws/r/db_instance.html#apply_immediately) boolean argument which affects whether any changes are applied immediately during the Terraform apply, or postponed until AWS's next scheduled maintenance window for that database.

The `apply_immediately` model isn't suitable here because the point is to leverage Terraform's planning engine to manage resource recreation where necessary.

I'm still a fan of this idea, but perhaps with differently named arguments, although I'm struggling to think of names to suggest.
>Maybe there could be 2 conflicting attributes - user_data and user_data_forcenew. One would be forcenew and users could choose which one to use.

Clearly one of the arguments needs to continue to be named `user_data`, but which one depends on your preference for backward-compatibility with v2.5 through v2.9, or for compatibility with v2.10+. You may decide the extra argument is `user_data_update_in_place`. 🤷

**Comment by displague** [comment]
Hi! I can also report that the [Linode](https://github.com/linode/terraform-provider-linode/blob/master/linode/resource_linode_instance.go#L81-L95) provider also treats this value as requiring a ForceNew.  In that situation, it felt like a judgement call because "rebuild" is an API action that could have been triggered rather than requiring a new provision. It really comes down to what the API offers and whether or not the user will get what they expect.

Could "reboot" or "reinstall" be a suitable compromise if the only change is to the UserData?  I've wondered [similar things](https://github.com/linode/terraform-provider-linode/issues/37#issuecomment-478609838) before.

### Reboot

I imagine a `reboot` won't cause the userdata to take effect in all cases? Is this correct?

### Reinstall

A [`reinstall`](https://www.packet.com/developers/docs/servers/key-features/reinstall/) to the same device would get the new `user_data` to apply.

Because the "apply" of this change would not destroy the resource, dependent `provisioner` resources would not be triggered. There may be other side effects to the device incurring downtime and having the disk wiped that could throw off other types of dependent resources.

For these reasons, **I think ForceNew is the correct behavior**, so how can we remedy the side-effects?

### Reservations

> Since particular server types are in limited supply in various Packet regions, we've found it more reliable to update the userdata in place and then re-image the existing server (the reinstall device API action). Destroying an existing server and then re-provisioning often leads to capacity errors, manual retries, and support ticket escalations.

Would [IP](https://www.packet.com/developers/docs/network/basic/ip-allocation/) and [Hardware reservations](https://www.packet.com/developers/docs/getting-started/deployment-options/reserved-hardware/) fit your needs, @jstangroome? I could see how a data resource for accessing hardware_reservations would be handy here.

https://github.com/terraform-providers/terraform-provider-packet/issues/241

**Comment by jstangroome** [comment]
@displague Hardware Reservations are tricky, and perhaps worth moving the discussion elsewhere. In short though, we've tried, and failed to find a clean way for Terraform to consume an available Hardware Reservation if it exists, and fallback to on-demand otherwise. I expect this would be even more difficult if the ForceNew is the reason why a Hardware Reservation suddenly became available mid-apply.

**Comment by displague** [comment]
[null_resource triggers](https://www.terraform.io/docs/provisioners/null_resource.html#triggers) could be used as a work-around to my provisioner concerns. My hunch is that in-resource provisioners would be adversely affected.

> If we use lifecycle { ignore_changes = ["user_data"] } to avoid the re-provision I believe we also lose the updating of the userdata.

Update logic is in place for this field, despite it being a ForceNew field.  

I can't tell from https://www.terraform.io/docs/configuration/resources.html#lifecycle-lifecycle-customizations how this should behave.  Would it prevent a destroy/create, or would it also prevent an upgrade?

**Comment by displague** [comment]
>  In short though, we've tried, and failed to find a clean way for Terraform to consume an available Hardware Reservation if it exists, and fallback to on-demand otherwise.

With a data resource (#241) this could be possible:

```
hardware_reservation_ids = coalesce(data.packet_hardware_reservation.large.id, data.packet_hardware_reservation.medium.id, "next-available")
```

**Comment by invidian** [comment]
Hm, as the original issue title is no longer the case, should new issue be created to track optional replacement?

**Comment by displague** [comment]
That sounds good to me, @invidian.

Given the conversation above, with the latest version of the provider, if this is still a problem for you, can you file a new issue to drive the provider toward your expectations? (@johananl @jstangroome @ivan-section-io)
