### ISSUE TITLE
improper handling of mixed disk "size" responses

### ISSUE THREAD

**Issue by displague** [packethost/terraform-provider-packet#247]
Device disk sizes are returned in an inconsistent format by the Packet API, such as the mix of string, integer, and unit-string results shown here:

```json
{
    "id": "uuid",
    "storage": {
        "disks": [
            {
                "device": "/dev/sdc",
                "partitions": [
                    {
                        "label": "BIOS",
                        "number": 1,
                        "size": "512M"
                    },
                    {
                        "label": "SWAP",
                        "number": 2,
                        "size": "3993600"
                    },
                    {
                        "label": "ROOT",
                        "number": 3,
                        "size": 0
                    }
                ],
                "wipeTable": true
            },
            ...
        ]
    },
    ...
}
```

As a result, errors such as `json: cannot unmarshal number into Go struct field .storage.disks.partitions.size of type string` are reported.

**Comment by displague** [comment]
Within an internal issue tracker, I've also reported this API response as an inconsistency.

**Comment by Jpnock** [comment]
Can confirm I've encountered this problem.

I believe the "storage" field was previously a string, rather than an object - hence the lack of validation on the field.

It seems the CPR documentation mixes string and integer types for the "size" field too which, if I remember correctly, causes the Device Creation API to return a 500 response code ([CPR docs](https://www.packet.com/developers/docs/servers/key-features/cpr/))

Additionally any existing server created with Terraform that uses both types for the size field causes Terraform to throw `json: cannot unmarshal number into Go struct field .storage.disks.partitions.size of type string` when running commands such as `terraform plan` or `terraform apply`

**Comment by ocobleseqx** [comment]
**NOTE: This project is Deprecated. The [Equinix provider](https://registry.terraform.io/providers/equinix/equinix/latest/docs) has full support for existing Terraform managed Equinix Metal (Packet) resources once Terraform configuration and state are adapted. The Equinix provider manages resources including Network Edge and Fabric in addition to Metal. [Please review the Packet to Equinix provider migration guide](https://registry.terraform.io/providers/equinix/equinix/latest/docs/guides/migration_guide_packet).**

This issue is outdated and has been inactive for almost 2 years. If this issue persist please open a [new issue in Terraform provider equinix repository. ](https://github.com/equinix/terraform-provider-equinix/issues/new?assignees=&labels=&template=bug.md&body=Linked%20issue:%20https://github.com/packethost/terraform-provider-packet/issues/247)
