### ISSUE TITLE
TestAccPacketSpotMarketRequest test is flaky

### ISSUE THREAD

**Issue by displague** [packethost/terraform-provider-packet#265]
The following test failed:
```
--- FAIL: TestAccPacketSpotMarketRequest_Basic (409.26s)
    testing.go:569: Step 0 error: After applying this step and refreshing, the plan was not empty:
```

This type of problem could be caused by:
* a resource whose values are independently manipulated (provider backend changes it after Terraform requests it), this can be resolved with a `DiffSuppressFunc`
* a resource whose values are not saved to state correctly after being fetched from the provider API (a missing or invalid `Set`)
* deletion or other test staging problems. some examples of solutions to these types of problems are presented here: https://github.com/packethost/terraform-provider-packet/pull/250/files#diff-1530342ef4e50de6fb418f850b5bf177R68-R80

_Originally posted by @displague in https://github.com/packethost/terraform-provider-packet/pull/261#issuecomment-702514245_

**Comment by ocobleseqx** [comment]
**NOTE: This project is Deprecated. The [Equinix provider](https://registry.terraform.io/providers/equinix/equinix/latest/docs) has full support for existing Terraform managed Equinix Metal (Packet) resources once Terraform configuration and state are adapted. The Equinix provider manages resources including Network Edge and Fabric in addition to Metal. [Please review the Packet to Equinix provider migration guide](https://registry.terraform.io/providers/equinix/equinix/latest/docs/guides/migration_guide_packet).**

This issue is outdated and has been inactive for almost 2 years. This test [is updated and expanded in Equinix Provider](https://github.com/equinix/terraform-provider-equinix/blob/850f5a8a3201a545ab9ec14f30f8c68529fce707/equinix/data_source_metal_spot_market_request_acc_test.go#L13-L49)

If this issue persist please open a [new issue in Terraform provider equinix repository. ](https://github.com/equinix/terraform-provider-equinix/issues/new?assignees=&labels=&template=bug.md&body=Linked%20issue:%20https://github.com/packethost/terraform-provider-packet/issues/265)
