### ISSUE TITLE
Error: Not Found when provisioning SSH key with packet_project_ssh_key

### ISSUE THREAD

**Issue by arctiqtim** [packethost/terraform-provider-packet#287]
Hi there!

Seeing an issue when trying to provision project SSH keys with Terraform.  The terraform apply fails with an Error: Not Found message when applying, however they key is actually created in the Packet console.

### Terraform Version
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/tls v2.2.0
+ provider registry.terraform.io/packethost/packet v3.1.0-alpha1

### Affected Resource(s)
- packet_project_ssh_key

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "packet_project_ssh_key" "anthos_ssh_key" {
  name       = "anthos_ssh_key"
  public_key = tls_private_key.anthos_ssh_key.public_key_openssh
  project_id = "<project_id>"
}
```

### Debug Output
https://gist.github.com/displague/bafa87cf5ec90bf6afeb77c65d8c275f

### Expected Behavior
The SSH key should be created and reported back to Terraform with success.

### Actual Behavior
The SSH key is created in Packet/Equinix Metal within the project. However due to this error, Terraform state doesn't reflect this.  A followup terraform apply will error since they key exists within Packet.

### Steps to Reproduce
1. `terraform apply`

**Comment by t0mk** [comment]
hey @arctiqtim thanks for reporting the issue. I will take a look and get back to you.

**Comment by displague** [comment]
This sounds similar to other reports we've seen here and on packngo when using a Project API Key (instead of a user API key).

The other report that comes to mind (I can't find an appropriate link) is that (IIRC) there is a `Location:` returned for the newly created ssh key, but the project API key doesn't have access to the key at that `Location:` URL (but it would be able to access the key by ID at the alternate URL (`/projects/ssh-keys/{id}` vs `/ssh-keys/{id}`).

**Comment by t0mk** [comment]
@arctiqtim thank you for thorough debug log, but firstly I have to ask you to rotate your API token, because you unfortunately pasted it in the Gist. I think we should put a warning about the API token to the PR template, it's an easy fauxpas to make, especially if you want to be helpful.

I've just now tried with the same conf with TF version 0.13.5, Packet provider version 3.1.0. On tf apply, I got an error 

```
2020/11/16 15:46:26 [DEBUG] packet_project_ssh_key.test: apply errored, but we're indicating that via the Error pointer rather than returning it: Key is not a valid SSH public key
2020/11/16 15:46:26 [ERROR] eval: *terraform.EvalApplyPost, err: Key is not a valid SSH public key
2020/11/16 15:46:26 [ERROR] eval: *terraform.EvalSequence, err: Key is not a valid SSH public key

Error: Key is not a valid SSH public key

  on main.tf line 5, in resource "packet_project_ssh_key" "test":
   5: resource "packet_project_ssh_key" "test" {
```

.. meaning that the provided string is not a valid SSH key. I didn't really test if the key is valid, but the API error was HTT 422, and the key resource WAS NOT created in the API. Are you sure that the key you are seeing is not some older key?

Can you please try again with newer TF? If the problem persist, I will get back to it.

**Comment by arctiqtim** [comment]
Thanks @t0mk for having a look!  And for the watchful eye on the presence of the token  👍 

That token was an ephemeral token so no worries there.  We have the Vault secrets engine running that Terraform is uing to have ephemeral project level API keys generated for each Terraform run.

I upgraded to the 3.1.0 release of the provider and no difference in the behaviour.  I think it needs to be a real key, since the issue is the 404 on the response back from Packet.  The key itself actually gets created.  So essentially on a tf apply the key gets created but the provider reports an error with the 404 back from packet.  A followup run will have tf try to create the resource again since it doesn't exist in state, and the error back will be that the key exists.  Remove the key in the console and re-run the tf plan again and I get the 404 response back again, but the key creates.

I'm positive it's not an older key, as when tf is creating the key I'm removing again afterwards to keep testing.

And indeed @displague we are using project-level API keys for this.  I'm going to try a test right now with a user API key and see if there is a change in behaviour

**Comment by arctiqtim** [comment]
I tested this with a user API key vs project API key and the terraform plan runs without issue FYI.  So definitely isolated to an issue with project level API keys

**Comment by t0mk** [comment]
@arctiqtim ah, I only tried with my user API key. I'll try with a project API key tomorrow, and if it's an API issue, I will try to report it.

**Comment by displague** [comment]
I ran into a similar behavior when making https://github.com/displague/metal-actions-example. I could not have a project API key delete the project and the key itself, so I needed the user key performing this task.

**Comment by displague** [comment]
There is a newline in the key, can you try removing that?

**Comment by arctiqtim** [comment]
Think I tried that using chomp but will have a look again.  Would seem odd that this would be the case for user vs project api key ... since the terraform code is unchanged, and I am using a data call to vault to retrieve the key.  So when I tested with user key I'm just using a different endpoint in Vault that's configured to dish out a user key instead of project.

```
data "vault_generic_secret" "packet_auth" {
  path = "packet/creds/usertoken"
}
provider "packet" {
  auth_token = data.vault_generic_secret.packet_auth.data.api_key_token
}
```

This is the code I'm using to get the ephemeral key ... so the only thing I did to get this working with a user API key instead of project, is I changed the role in vault for packet/roles/usertoken to a user type role instead of project.

**Comment by displague** [comment]
https://github.com/packethost/vault-plugin-secrets-packet/issues/11 seems related

**Comment by t0mk** [comment]
@arctiqtim I tested with project API key and got the same error. I created issue in packngo, hopefully we can get someone from Equinix Metal to look at this. Thanks again for reporting.

**Comment by arctiqtim** [comment]
No problem @t0mk happy to help

@displague I haven't had any issues with the Vault provider revoking project API keys it generates but I've config'd the Vault backend (packet/config) to use a user API key :)

**Comment by displague** [comment]
Project API keys can now successfully create and destroy project SSH keys.  This change was on the Equinix Metal API side (and benefits the [Equinix Metal](https://github.com/equinix/terraform-provider-metal/issues/1) and Packet provider equally).

Please reopen the issue if the problem is not resolved, @arctiqtim.

If you find other limitations with the project API key use in Terraform, please open a new issue on the Equinix Metal provider: https://github.com/equinix/terraform-provider-metal/issues/.
